export const exifKeyMap: Record<keyof IExifData, string> = {
  Make: "厂商",
  Model: "型号",
  Orientation: "方向",
  XResolution: "X 分辨率",
  YResolution: "Y 分辨率",
  ResolutionUnit: "分辨率单位",
  Software: "软件",
  ModifyDate: "修改日期",
  YCbCrPositioning: "YCbCr 位置",
  ExposureTime: "曝光时间",
  FNumber: "光圈",
  ExposureProgram: "曝光程序",
  ISO: "ISO",
  SensitivityType: "感光度类型",
  RecommendedExposureIndex: "推荐曝光指数",
  ExifVersion: "Exif 版本",
  DateTimeOriginal: "日期时间原始",
  CreateDate: "创建日期",
  OffsetTime: "时差",
  OffsetTimeOriginal: "时差原始",
  OffsetTimeDigitized: "时差数字化",
  CompressedBitsPerPixel: "压缩位每像素",
  ExposureCompensation: "曝光补偿",
  MeteringMode: "测光模式",
  LightSource: "光源",
  Flash: "闪光灯",
  FocalLength: "焦距",
  SubSecTime: "子秒时间",
  SubSecTimeOriginal: "子秒时间原始",
  SubSecTimeDigitized: "子秒时间数字化",
  FlashpixVersion: "Flashpix 版本",
  ColorSpace: "颜色空间",
  ExifImageWidth: "图像宽度",
  ExifImageHeight: "图像高度",
  SensingMethod: "感光方法",
  FileSource: "文件源",
  SceneType: "场景类型",
  ExposureMode: "曝光模式",
  WhiteBalance: "白平衡",
  SceneCaptureType: "场景捕获类型",
  GainControl: "增益控制",
  Contrast: "对比度",
  Saturation: "饱和度",
  Sharpness: "锐度",
  SerialNumber: "序列号",
  LensInfo: "镜头信息",
  LensMake: "镜头制造商",
  LensModel: "镜头型号",
  LensSerialNumber: "镜头序列号",
  CustomRendered: "自定义渲染",
  FocalLengthIn35mmFormat: "35mm 格式焦距",
  SubjectDistanceRange: "主体距离范围",
  ImageNumber: "图像编号",
  Lens: "镜头",
};

export const getExifKeyLabel = (key: string) => {
  return exifKeyMap[key as keyof typeof exifKeyMap] || key;
};
